### ISSUE TITLE
Update for ujson 3.0

### ISSUE THREAD

**Issue by Amertz08** [Amertz08/drf_ujson2#12]
Looks like usjon 3.0 dropped. Need to make sure it is fully supported.
https://github.com/ultrajson/ultrajson/releases/tag/3.0.0

**Comment by johnthagen** [comment]
Isn't `ujson` 3.0 already used in tests since there is no upper bound on the requirement?

https://github.com/Amertz08/drf_ujson2/blob/d3fc8d4f9f60f9bda53881b9a57739119874722a/setup.py#L22

**Comment by Amertz08** [comment]
Yeah. I think I just made this as a reminder to go over the various ujson3 stuff and make sure nothing broke.

**Comment by Amertz08** [comment]
I am not seeing any issues.
