### ISSUE TITLE
Advertise JSON decoder more visibly?

### ISSUE THREAD

**Issue by hartwork** [Amertz08/drf_ujson2#4]
Hi!

I think the JSON decoding part is at least as interesting as the encoding part (because it's faster and rejects single surrogates as invalid). So it's great you move off `drf-ujson-renderer` for a name. However the descriptions have not caught up yet: On the GitHub repo, on PyPI and in the readme. I propose these changes:

```diff
--- Django Rest Framework UJSON Renderer
+++ Django Rest Framework UJSON Parser and Renderer

--- Django Rest Framework renderer using ujson
+++ Django Rest Framework JSON parser and renderer using ujson

--- New repo for forked from https://github.com/Amertz08/drf-ujson-renderer
+++ JSON parser and renderer using ujson for Django Rest Framework
```

PS: This page I created today may be of interest: https://djangopackages.org/grids/g/drf-json-decoder-integration/

**Comment by Amertz08** [comment]
Hey yeah that sounds good. Thanks for creating that page.

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
