### ISSUE TITLE
Not working with ujson 2.0.0

### ISSUE THREAD

**Issue by pasevin** [Amertz08/drf_ujson2#6]
ujson 2.0.0 has removed ```double_precision``` and ```precise_float``` so this lib crashes now.

https://github.com/ultrajson/ultrajson/releases/tag/2.0.0
https://github.com/ultrajson/ultrajson/commit/eb7d894f225bb89d269188ba6ec559b914a71b8a

**Comment by Amertz08** [comment]
Yeah just ran into this myself. Going to do a bug fix release pinning `ujson<2` then implement a fix.

**Comment by Betalos** [comment]
Any progress on this one ???
